version: '3.8'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    networks:
      - frontend
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    depends_on:
      - server
    environment:
      - SERVER=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true

  server:
    build: ./server
    ports:
      - '5000:5000'
    networks:
      - backend
      - frontend
    environment:
      - OCR=http://ocr:5000
      - MONGO=mongodb://db:27017
      - CLIENT=http://localhost:3000
    volumes:
      - ./server/src:/usr/src/app/src
      - images:/usr/src/app/images
      - recipes:/usr/src/app/recipes
    depends_on:
      - db
      - ocr

  ocr:
    build: ./ocr
    ports:
      - '5001:5000'
    networks:
      - backend
    environment:
      - MONGO=mongodb://db:27017
      - SERVER=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./ocr/src:/usr/src/app/src
    depends_on:
    - db

  db:
    image: mongo:3.6.19-xenial
    ports:
      - 27017:27017
    networks:
      - backend
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb


networks:
  backend:
  frontend:

volumes:
  images:
  recipes:
  mongo-data:
  mongo-config: