version: '3.8'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    networks:
      - frontend
    volumes:
      - ./client/src:/usr/src/app/src
      - ./client/public:/usr/src/app/public
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER=http://localhost:5000
      - CHOKIDAR_USEPOLLING=true

  server:
    build: ./server
    ports:
      - '5000:5000'
    networks:
      - backend
      - frontend
    environment:
      - MONGO_URL=mongodb://db:27017
      - CLIENT=http://localhost:3000
    volumes:
      - ./server/src:/usr/src/app/src
    depends_on:
      - db

  db:
    image: mongo:3.6.19-xenial
    ports:
      - 27017:27017
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  mongo-data: